#!/bin/bash

echo "Dashboard Performance Test Instructions"
echo "======================================="
echo ""
echo "1. Run the dashboard with: npm run dashboard"
echo ""
echo "2. Test status updates (space key):"
echo "   - Press space on any task to cycle through statuses"
echo "   - Notice immediate UI response (no freezing)"
echo "   - Status bar shows save progress"
echo ""
echo "3. Test task creation (a/A keys):"
echo "   - Press 'a' to add a sibling task"
echo "   - Press 'A' (Shift+a) to add a child task"
echo "   - Notice the editor opens immediately"
echo "   - After saving in editor, watch the status progression:"
echo "     • 'Creating task...' → 'Saving task...' → 'Finalizing task...' → 'Task created successfully'"
echo "   - The new task appears immediately with no freezing"
echo "   - VERIFY: The task should have a real ID (not temp-xxxxx)"
echo ""
echo "4. Test task persistence:"
echo "   - Create a few new tasks"
echo "   - Exit the dashboard (q or Ctrl+C)"
echo "   - Restart the dashboard"
echo "   - VERIFY: All newly created tasks should still be there"
echo ""
echo "5. Test rapid actions:"
echo "   - Press space multiple times quickly"
echo "   - Navigate with arrow keys while saving"
echo "   - Create multiple tasks in succession"
echo ""
echo "The dashboard should remain responsive throughout!"
echo "Watch the status bar for save indicators: ● Unsaved → 💾 Saving... → ✓ Saved"
echo ""
echo "If tasks aren't being saved:"
echo "   - Check that you see all status messages during creation"
echo "   - Ensure the 'Finalizing task...' step completes"
echo "   - Look for any error messages in the status bar"
echo ""
echo "Press Enter to start the dashboard..."
read

npm run dashboard 